import 'package:all_in_one_brainrot/models/options.dart';

const List<Options> italianBrainrotOptions = [
  Options(
    name: "Tralalero Tralala",
    imgPath: "images/Tralalero_Tralala.jpg",
    soundPath: "sound/Tralalero_Tralala.mp3",
    description: "On the beach, there stands an intriguing shark character sporting three legs and fashionable Nike sneakers. This unique figure marks the inception of the Italian creation known as Brainot Mim, which is defined by its competitive spirit against Bardiro Crocodilo. The narrative intricately weaves this rivalry into its backdrop, highlighting a playful hobby shared by characters like the adorable baby sharks, affectionately referred to as the Tralalaleritos. These little sharks embody cuteness and charm, adding a delightful element to the story.",
    conclusionAi: "Behold! A mysterious shark with THREE legs wearing cool Nike sneakers prowls the beach! This is where the legendary Italian Brainrot saga began, sparking an epic rivalry with the fearsome Bombardiro Crocodilo. And guess what? This shark has adorable babies called Tralalaleritos!",
  ),
  Options(
    name: "Bombardiro Crocodilo",
    imgPath: "images/Bombardiro_Crocodilo.jpg",
    soundPath: "sound/Bombardiro_Crocodilo.mp3",
    description: "This distinctive character represents a fascinating synthesis between bombers and crocodiles. Originating from Italian concepts like \"Brainot\" and evolving into \"Tralaller\" and \"Tralala,\" this character is often accompanied by the distinctive sound effect \"Tung Tung Tung Tung Tung Tung Tung Tung Hut.\" While featuring a crocodile's head as its most recognizable feature, the body appears to draw significant inspiration from World War II American military aircraft—specifically bombers such as the B-17 Flying Fortress and B-25 Mitchell. According to various characterizations, this entity allegedly rejects Allah's teachings and engages in bombing operations targeting children in Palestinian territories and Gaza. The character \"Tralaller\" is frequently portrayed in an antagonistic relationship with \"Tralala.\" Its primary combat strategy involves aerial bombardment, establishing it as a formidable opponent from above. Nevertheless, the character demonstrates considerable vulnerability in close-range combat scenarios, evidenced by numerous defeats when confronted by \"tung tung tung tung.\" Within Korean communities, this character is commonly misidentified as \"Bombardi O\" or \"Spring Bardil\" rather than its actual designation \"Bombiri.\"",
    conclusionAi: "What happens when you mix a terrifying crocodile with a WWII bomber plane? You get this legendary flying beast! With a crocodile head and aircraft body, it rules the skies and battles its eternal rival, Tralalero Tralala. But beware—it has a secret weakness in close combat!",
  ),
  Options(
    name: "Tung Tung Hurar Tung Tung Tung Sahur",
    imgPath: "images/Tung_Tung_Hurar_Tung_Tung_Tung_Sahur.jpg",
    soundPath: "sound/Tung_Tung_Hurar_Tung_Tung_Tung_Sahur.mp3",
    description: "A brown wooden figure grips a baseball bat, its face reminiscent of a Thomas the Tank Engine and Aoni, creating an unsettling sense of the uncanny valley. It is said that if you fail to respond to this character's name three times, you will find yourself at the home of the person associated with it, a location described as quite frightening and eerie.",
    conclusionAi: "A creepy wooden creature clutches a baseball bat, with a face that looks like Thomas the Train gone WRONG! Legend whispers that if you ignore its name three times... it might just show up at YOUR door! Spooky, right?",
  ),
  Options(
    name: "Lirilì Larilà",
    imgPath: "images/Lirilì_Larilà.jpg",
    soundPath: "sound/Lirilì_Larilà.mp3",
    description: "The concept of elephant characters adorned with cactuses and sporting sandals often evokes the image of a unique clock that possesses the ability to halt time during battles. This intriguing idea primarily emphasizes the notion of evading direct conflict; however, when it comes to technical combat, these elephant characters leverage their distinctive physique and lengthy trunks to demonstrate their formidable strength.",
    conclusionAi: "An elephant wearing cactuses and sandals with a magical power to STOP TIME! This clever creature prefers to avoid fights, but when cornered, watch out—its powerful trunk packs a serious punch!",
  ),
  Options(
    name: "Boneca Ambalabu",
    imgPath: "images/Boneca_Ambalabu.jpg",
    soundPath: "sound/Boneca_Ambalabu.mp3",
    description: "Initially, the character emerged as a creation featuring the face of Dreamybull, combined with elements of a da-couple, and it quickly gained traction in Indonesia. During a family vacation, an unusual incident occurred where oil unexpectedly gushed from the ground, resulting in a bizarre figure with a frog’s head, a tire for a torso, and human legs.",
    conclusionAi: "Born from a bizarre accident when oil exploded from the ground during a family vacation! This weird creature has a FROG HEAD, a TIRE for a body, and walks on human legs. Indonesia's strangest creation!",
  ),
  Options(
    name: "Brr Brr Patapim",
    imgPath: "images/Brr_Brr_Patapim.jpg",
    soundPath: "sound/Brr_Brr_Patapim.mp3",
    description: "A captivating character adorned with the distinctive head of a cozu monkey perches vigilantly upon the branches of ancient trees. This forest sentinel actively defends its woodland domain by launching counterattacks against those who dare to trespass—either commanding tree roots to ensnare intruders or cleverly constructing traps to ambush unwelcome visitors. Though formally named \"Pata Pim,\" this guardian became widely recognized by the curious sound \"Brer Brarr,\" which actually originates from a blue frog called \"slim\" residing within a golden hat the character discovered during its forest wanderings. The lore tells us that despite the slim's persistent resistance from within the hat, Pata Pim—following the sage counsel of a forest wizard—ultimately resolves the situation by inflating a balloon that gently carries the slim away. This whimsical narrative provides a more wholesome and accessible backstory compared to alternative explanations that might involve peculiar or inappropriate language.",
    conclusionAi: "Deep in the ancient forest lives a monkey-headed guardian who protects the trees! It can command roots to trap intruders and sets clever traps for unwelcome visitors. The mysterious blue frog in its golden hat makes the famous 'Brer Brarr' sound!",
  ),
  Options(
    name: "Chimpanzini Bananini",
    imgPath: "images/Chimpanzini_Bananini.jpg",
    soundPath: "sound/Chimpanzini_Bananini.mp3",
    description: "A character features green chimpanzees nestled within a banana. Upon exiting the quiz video that reveals the character’s name, many individuals are inclined to share this video with someone who resembles a shipphanny. If you peel away the banana, you will discover toned muscles hidden beneath.",
    conclusionAi: "A sneaky green chimpanzee hiding inside a giant banana! But here's the SECRET—peel away the banana and you'll discover SUPER STRONG muscles underneath! Not just a cute fruit creature after all!",
  ),
  Options(
    name: "Bombombini Gusini",
    imgPath: "images/Bombombini_Gusini.jpg",
    soundPath: "sound/Bombombini_Gusini.mp3",
    description: "A character that uniquely fuses elements of a goose and a bomber aircraft. It is likely that the design is inspired by the B-29 model, notable for its four engines. This character emerges as a formidable force against the Bombardi Crocodilo and is also depicted as the sibling of Bardiro Crocodilo. Additionally, he takes pleasure in the act of bombing individuals. In Italian pronunciation, the \"s\" between vowels is articulated distinctly, which is why Guini is pronounced rather than Gugini.",
    conclusionAi: "A GOOSE merged with a four-engine bomber plane! This mighty flying creature is the sibling of Bombardiro Crocodilo and one of the few who can stand against it in aerial combat. Honk honk... BOOM!",
  ),
  Options(
    name: "Cappuccino Assassino",
    imgPath: "images/Cappuccino_Assassino.jpg",
    soundPath: "sound/Cappuccino_Assassino.mp3",
    description: "Copuccino Coffee Circle introduces a character known as an assassin, equipped with a knife and a unique limb. This character is renowned for their incredible speed, rumored to be swift enough to pursue the elusiveTripy Trophythat moves rapidly through the water. Additionally, Capuccina, the ballerina and spouse of this assassin, has a backstory that involves a childhood encounter with the fearsome Bombiri Crocodilo, which suggests that their origins may trace back to this very district.",
    conclusionAi: "A coffee cup turned deadly assassin! Armed with a knife and blessed with LIGHTNING SPEED, this caffeinated killer is fast enough to chase the speediest creatures through water. Married to the beautiful Ballerina Cappuccina!",
  ),
  Options(
    name: "Trippi Troppi",
    imgPath: "images/Trippi_Troppi.jpg",
    soundPath: "sound/Trippi_Troppi.mp3",
    description: "fat bears and fish are treated as 'Tropha Tripa'",
    conclusionAi: "A chubby bear-fish combo known as Tropha Tripa! This adorable yet mysterious creature waddles around leaving everyone wondering—is it a bear that swims or a fish that walks?",
  ),
  Options(
    name: "Frigo Camelo",
    imgPath: "images/Frigo_Camelo.jpg",
    soundPath: "sound/Frigo_Camelo.mp3",
    description: "The character in question is a whimsical fusion of a camel and a refrigerator, complete with footwear. From its mouth escapes a gust of cold air, occasionally so frigid that it can freeze.",
    conclusionAi: "A CAMEL with a REFRIGERATOR body wearing shoes! It breathes ICY COLD air from its mouth—so cold it can FREEZE anything in its path! Perfect for hot desert days... or freezing your enemies!",
  ),
  Options(
    name: "La Vaca Saturno Saturnita",
    imgPath: "images/La_Vaca_Saturno_Saturnita.jpg",
    soundPath: "sound/La_Vaca_Saturno_Saturnita.mp3",
    description: "This character, depicting a unique fusion of human feet and a cow's head atop the body of Saturn, makes its grand appearance during festival celebrations. With each step it takes, the movement resembles a captivating dance, inviting joy and amusement from onlookers. Similar to Lyrili Larila, the accompanying video may be brief due to its narrative focus on conflict avoidance. Nonetheless, this character represents a formidable player, wielding a power that resonates on a cosmic scale, akin to a black hole.",
    conclusionAi: "A COW'S HEAD on SATURN'S BODY with human feet! This cosmic dancer only appears during festivals, dancing with each step. Don't be fooled by its silly moves—it wields the power of a BLACK HOLE!",
  ),
  Options(
    name: "Ballerina Cappucina",
    imgPath: "images/Ballerina_Cappucina.jpg",
    soundPath: "sound/Ballerina_Cappucina.mp3",
    description: "She is an extraordinary ballerina whose head is replaced by a coffee mug. Once married to Cappuccino Assassino, she is now known as Siren. Typically, she captivates audiences with her graceful dancing or enchanting singing performances.",
    conclusionAi: "A graceful ballerina with a COFFEE MUG for a head! Once married to the deadly Cappuccino Assassino, she now enchants everyone with her beautiful dancing and siren-like singing. Don't fall under her spell!",
  ),
  Options(
    name: "U Din Din Din Din Dun Ma Din Din Din Dun",
    imgPath: "images/U_Din_Din_Din_Din_Dun_Ma_Din_Din_Din_Dun.jpg",
    soundPath: "sound/U_Din_Din_Din_Din_Dun_Ma_Din_Din_Din_Dun.mp3",
    description: "This character embodies a striking physique reminiscent of a bodybuilder, complete with vibrant orange hair. In the majority of videos, the second image featuring this character is more frequently showcased. While it may not have a prominent role in the versus video, it is portrayed as a robust figure, albeit with a slight imperfection on the head of Tung Tung Safre. The character is affectionately nicknamed 'U DIN DIN DUN MA DIN DIN DUN,' a playful abbreviation of a longer title. Interestingly, there exists a backstory suggesting that this character's transformation into an orange was triggered by an ordinary individual's consumption of orange seeds.",
    conclusionAi: "A MASSIVE bodybuilder with wild orange hair! Legend says an ordinary person ate too many orange seeds and transformed into this muscular beast! One of the strongest characters in the Brainrot universe!",
  ),
  Options(
    name: "Trulimero Trulicina",
    imgPath: "images/Trulimero_Trulicina.jpg",
    soundPath: "sound/Trulimero_Trulicina.mp3",
    description: "Trulimero Trulicina represents a fascinating hybrid creature, combining the traits of a cat and a fish, while uniquely possessing human legs. This unusual appearance was triggered by an incident involving Bombardiro Crocodilo, who bombarded a nearby beach, leading to the emergence of Trulimero's distinctive form.",
    conclusionAi: "A CAT-FISH hybrid walking on human legs! This strange creature was created when Bombardiro Crocodilo bombed a beach—the explosion somehow fused a cat, a fish, and human legs together! Meow... splash... stomp!",
  ),
  Options(
    name: "Girafa Celeste",
    imgPath: "images/Girafa_Celeste.jpg",
    soundPath: "sound/Girafa_Celeste.mp3",
    description: "La Baca Saturno Saturita embodies a universal archetype, much like the renowned battles associated with it. Furthermore, upon a detailed examination of the image, one can observe La Baka Saturno Saturita gracefully suspended in the sky.",
    conclusionAi: "A celestial giraffe floating gracefully in the sky! Look closely and you might spot La Vaca Saturno Saturnita hovering nearby. This cosmic creature holds secrets of the universe in its long neck!",
  ),
  Options(
    name: "Bobrito Bandito",
    imgPath: "images/Bobrito_Bandito.jpg",
    soundPath: "sound/Bobrito_Bandito.mp3",
    description: "This character is a beaver, distinctively adorned with a menstruation and wielding a Tommy gun. He is often depicted with a firearm in one hand and a cigarette in the other, suggesting that he might be affiliated with the world of gangsters. The iconic phrase associated with this character is the catchy template: 'OI OI OI, Bobrito Bandito?!'",
    conclusionAi: "A tough beaver gangster wielding a Tommy gun! This forest outlaw always has a mischievous look and a catchy catchphrase: 'OI OI OI, Bobrito Bandito?!' Don't mess with this furry criminal mastermind!",
  ),
  Options(
    name: "Ta Ta Ta Ta Ta Ta Ta Ta Ta Ta Ta Sahur",
    imgPath: "images/Ta_Ta_Ta_Ta_Ta_Ta_Ta_Ta_Ta_Ta_Ta_Sahur.jpg",
    soundPath: "sound/Ta_Ta_Ta_Ta_Ta_Ta_Ta_Ta_Ta_Ta_Ta_Sahur.mp3",
    description: "This character is a fascinating amalgamation of various elements, including kettles, legs, arms, and facial features. Whenever it experiences sadness, it continuously sheds tears, producing steam at the kettle's spout. Its bond with Tung Tung Saru is particularly strong, and it tends to exhibit aggressive behavior towards others, reminiscent of the actions of Tung Tung Hur.",
    conclusionAi: "A walking KETTLE with arms, legs, and a face! When it gets sad, it cries endlessly and STEAM shoots out of its spout! Best friends with Tung Tung Sahur and gets quite aggressive toward strangers!",
  ),
  Options(
    name: "Pot hotspot",
    imgPath: "images/Pot_hotspot.jpg",
    soundPath: "sound/Pot_hotspot.mp3",
    description: "Pot Hotspot embodies an anthropomorphic character generated by artificial intelligence, characterized by a skeletal form that sports a human-like visage. This quirky figure yearns for Wi-Fi connectivity, often depicted with a smartphone displaying the word \"Wi-Fi.\"",
    conclusionAi: "A spooky skeleton creature desperately searching for Wi-Fi! Always seen holding a phone showing 'Wi-Fi'—this digital ghost just wants to connect to the internet! The modern monster of our age!",
  ),
  Options(
    name: "Frulli Frulla",
    imgPath: "images/Frulli_Frulla.jpg",
    soundPath: "sound/Frulli_Frulla.mp3",
    description: "Frulli Frulla is an energetic, hummingbird-like being that appears as though it has emerged directly from a vibrant smoothie blender. As per the imaginative tales created by fans, Frulli was originally just a typical green hummingbird. However, its fate took a wild turn when it accidentally drank from a bowl of frullato—an Italian fruit smoothie—that had been carelessly abandoned by a quirky scientist.",
    conclusionAi: "A hummingbird that looks like it flew straight out of a SMOOTHIE BLENDER! Once a normal green bird, it accidentally drank a magical fruit smoothie left behind by a quirky scientist and transformed forever!",
  ),
  Options(
    name: "Brri Brri Bicus Dicus Bombicus",
    imgPath: "images/Brri_Brri_Bicus_Dicus_Bombicus.jpg",
    soundPath: "sound/Brri_Brri_Bicus_Dicus_Bombicus.mp3",
    description: "A magnificent bird adorned with a distinctive raspberry necklace stands proudly, cloaked in spectacular gold and crimson gladiatorial armor complemented by a flowing cape, with the iconic Colosseum serving as the dramatic backdrop. Rather than typical avian appendages, this extraordinary creature possesses human feet encased in traditional Roman sandals. Throughout the original footage, the haunting melody of 'The Sound of Your Fear' accompanies this striking visual presentation. Brri Brri Bicus Dicus Bombicus represents a historically-inspired character within theItalian BrainrotUniverse (IBU), masterfully blending avian elements with classical Roman imperial aesthetics and the unique touch of a raspberry ornament around his neck. This remarkable combination results in a captivating character that successfully marries ancient militaristic traditions with peculiar natural elements, creating an entity that transcends conventional character design boundaries.",
    conclusionAi: "A GLADIATOR BIRD wearing golden armor and a raspberry necklace, standing before the mighty Colosseum! With human feet in Roman sandals and a flowing cape, this warrior bird is ready for battle! Ave, Brri Brri!",
  ),
  Options(
    name: "Tric Trac baraboom",
    imgPath: "images/Tric_Trac_baraboom.jpg",
    soundPath: "sound/Tric_Trac_baraboom.mp3",
    description: "Squirrels , zucchini and human feet are synthesized. BrerBrarr Patta Pimis called his cousin. Because of this, BGM is the same with each other and the content of the explanation is almost the same.",
    conclusionAi: "A squirrel fused with a zucchini and human feet! This quirky creature is the COUSIN of Brr Brr Patapim—that's why they share the same catchy music! Family reunions must be WILD!",
  ),
  Options(
    name: "Cocofanto Elefanto",
    imgPath: "images/Cocofanto_Elefanto.jpg",
    soundPath: "sound/Cocofanto_Elefanto.mp3",
    description: "Accompanied by the eerie tones of \"The Sound Of Your Fear,\" Cocofanto Elefanto stands out with its distinctive visual design. The character features an elephant’s head and trunk that emerge from a coconut shell, crafting a compact and striking silhouette. This aesthetic simplicity offers a sharp contrast to the more intricately designed figures, such as Bombardiro Crocodilo, thereby highlighting its unique charm in the lineup of menacing characters.",
    conclusionAi: "An elephant head poking out of a COCONUT SHELL! With 'The Sound of Your Fear' playing in the background, this tiny but terrifying creature proves that big scares come in small packages!",
  ),
  Options(
    name: "Burbaloni Lulilolli",
    imgPath: "images/Burbaloni_Lulilolli.jpg",
    soundPath: "sound/Burbaloni_Lulilolli.mp3",
    description: "This extraordinary character features a capybara nestled within the confines of a coconut shell. The phenomenon occurs along the pristine coastline of Bali, where such sightings are considered exceptionally rare and precious. When this remarkable creature makes its appearance, local residents come together in joyous celebration, gathering around crackling bonfires to honor and welcome the arrival of Burbaloni Lilylololi. What makes this event so special? The sheer rarity of witnessing such a unique combination of elements transforms each sighting into a community celebration that brings people together in shared wonder and reverence.",
    conclusionAi: "A CAPYBARA inside a COCONUT on Bali's beaches! Spotting this rare creature is so special that locals gather around bonfires to celebrate! One of the rarest and most precious sightings in the Brainrot world!",
  ),
  Options(
    name: "Orangutini Ananasini",
    imgPath: "images/Orangutini_Ananasini.jpg",
    soundPath: "sound/Orangutini_Ananasini.mp3",
    description: "It is a combination of orangutan and pineapple . The explanation is similar to that of the ship chini.",
    conclusionAi: "An ORANGUTAN merged with a PINEAPPLE! This tropical primate-fruit combo swings through the jungle looking absolutely delicious—but definitely not edible! A fruity friend with attitude!",
  ),
  Options(
    name: "Garamararamararaman dan Madudungdung tak tuntung perkuntung",
    imgPath: "images/Garamararamararaman_dan_Madudungdung_tak_tuntung_perkuntung.jpg",
    soundPath: "sound/Garamararamararaman_dan_Madudungdung_tak_tuntung_perkuntung.mp3",
    description: "This character embodies a unique combination of a person's facial features and feet, represented within the intriguing context of the salt and honey duality. The salt container is referred to as karamarahman, while the honey container is known as Madungdong. Notably, this character is said to emerge predominantly during the Ramadan season. Historically, they were once close companions who shared a bond through song, harmonizing about 'salt and honey,' until their friendship soured and transformed into animosity. This character hails from Indonesia, alongside another character, Tungung Tung Tung Tung Tung Hur.",
    conclusionAi: "TWO characters—one made of SALT, one made of HONEY! They used to be best friends singing together, but now they're ENEMIES! They only appear during Ramadan season. What tore their friendship apart? The mystery remains!",
  ),
  Options(
    name: "Il Cacto Hipopotamo",
    imgPath: "images/Il_Cacto_Hipopotamo.jpg",
    soundPath: "sound/Il_Cacto_Hipopotamo.mp3",
    description: "Introducing a captivating hybrid character from Lirilly Larila, known as the Hippo Burr. This unique figure is characterized by its distinctive cactus torso, adorned with stylish sandals that add a quirky flair. The origins of its peculiar toilet design remain a mystery, leaving fans to speculate about its significance. In the VS video, players have the ability to summon a small hippopotamus from the watch of Lirilla Larila. Although this little companion may not boast exceptional combat abilities, it certainly brings a charming element to the gameplay, having even managed to kick itself onto the scene alongside Lirilla Larila.",
    conclusionAi: "A HIPPO with a CACTUS body wearing stylish sandals! This creature can be summoned from Lirili Larila's magical watch! Not the strongest fighter, but definitely one of the WEIRDEST looking!",
  ),
  Options(
    name: "Blueberrinni Octopussini",
    imgPath: "images/Blueberrinni_Octopussini.jpg",
    soundPath: "sound/Blueberrinni_Octopussini.mp3",
    description: "The character's upper body resembles that of an octopus, adorned with a blueberry. Its diminutive size, comparable to that of a blueberry, allows it to deftly evade incoming attacks.",
    conclusionAi: "A TINY octopus wearing a blueberry—as small as the berry itself! Its secret power? Being SO SMALL that no attack can ever hit it! The ultimate dodge master of the Brainrot universe!",
  ),
  Options(
    name: "Glorbo Fruttodrillo",
    imgPath: "images/Glorbo_Fruttodrillo.jpg",
    soundPath: "sound/Glorbo_Fruttodrillo.mp3",
    description: "This character features a head and legs resembling those of a crocodile, perched atop a watermelon. Its primary habitat consists of swampy areas, and it boasts a weight of approximately 304 kilograms.",
    conclusionAi: "A crocodile head and legs sitting on a giant WATERMELON body! This 304-kilogram beast lurks in murky swamps, waiting for unsuspecting visitors. Refreshing fruit or terrifying reptile? BOTH!",
  ),
  Options(
    name: "Rhino Toasterino",
    imgPath: "images/Rhino_Toasterino.jpg",
    soundPath: "sound/Rhino_Toasterino.mp3",
    description: "What sets this character apart within the expansive array of personalities is its unique duality, existing simultaneously in both domestic and wild environments. Fan narratives often portray it as a crucial mediator, connecting household figures such as Capuccino Assassino with the untamed creatures like Glorbo Fruttodrillo. This intermediary function has led to Rhino Toasterino being frequently featured in transitional scenes in compilation videos, symbolizing the journey between the civilized and the wild realms of theItalian Brainrotuniverse.",
    conclusionAi: "A RHINO fused with a TOASTER! This unique creature lives in BOTH houses and the wild—it's the bridge between the civilized coffee cup characters and the savage fruit-animal hybrids! Breakfast AND danger!",
  ),
  Options(
    name: "Zibra Zubra Zibralini",
    imgPath: "images/Zibra_Zubra_Zibralini.jpg",
    soundPath: "sound/Zibra_Zubra_Zibralini.mp3",
    description: "The zebra character, known for its watermelon-like body paired with human legs, intriguingly bears a name that does not directly reference watermelon. However, the term \"Arbuz,\" which cleverly rearranges to form \"ZUBRA,\" translates to watermelon in Polish, hinting at the underlying inspiration behind its design.",
    conclusionAi: "A ZEBRA with a WATERMELON body walking on human legs! Here's a SECRET: 'ZUBRA' rearranges to 'ARBUZ'—which means WATERMELON in Polish! A hidden code in the name itself!",
  ),
  Options(
    name: "Graipussi Medussi",
    imgPath: "images/Graipussi_Medussi.jpg",
    soundPath: "sound/Graipussi_Medussi.mp3",
    description: "This unique character merges the qualities of grapes and Medusa, intriguing many with its unusual combination. Legend has it that this fascinating entity was discovered in the depths of the Pacific Ocean. The Grey Push Medusi stands out for its exceptional taste and milder texture compared to other jellyfish, which has made it a sought-after catch among fishermen. Unfortunately, this demand has led to a significant decline in its population.",
    conclusionAi: "GRAPES combined with MEDUSA from the deep Pacific Ocean! This legendary jellyfish-grape creature tastes better than other jellyfish—but fishermen caught so many that it's now SUPER RARE! Will you ever see one?",
  ),
  Options(
    name: "Tigrrullini Watermellini",
    imgPath: "images/Tigrrullini_Watermellini.jpg",
    soundPath: "sound/Tigrrullini_Watermellini.mp3",
    description: "Tigrrullini Watermellini stands out as one of the most visually captivating beings within theItalian Brainrotuniverse. This intriguing character merges the ferocious instincts of a tiger with the refreshing, hydrating essence of a watermelon. The resulting combination gives rise to a persona characterized by its inherent contradictions—simultaneously menacing and nurturing.",
    conclusionAi: "A FEROCIOUS TIGER with a juicy WATERMELON body! Is it dangerous or refreshing? BOTH! This creature is full of contradictions—ready to pounce AND quench your thirst at the same time!",
  ),
  Options(
    name: "Tracotucotulu Delapeladustuz",
    imgPath: "images/Tracotucotulu_Delapeladustuz.jpg",
    soundPath: "sound/Tracotucotulu_Delapeladustuz.mp3",
    description: "Tracotucotulu Delapeladustuz is a Volkswagen Beetle Camel, which combines a camel and a car (Volkswagen Beetle).",
    conclusionAi: "A CAMEL merged with a VOLKSWAGEN BEETLE car! This desert vehicle-animal can drive AND walk through sand dunes! The ultimate road trip companion with built-in humps for extra storage!",
  ),
  Options(
    name: "Gorillo Watermellondrillo",
    imgPath: "images/Gorillo_Watermellondrillo.jpg",
    soundPath: "sound/Gorillo_Watermellondrillo.mp3",
    description: "It is a gorilla that wears a watermelon like a nashi.",
    conclusionAi: "A mighty GORILLA wearing a WATERMELON like a hat! This fruity ape pounds its chest with pride, showing off its refreshing headgear to all the jungle creatures!",
  ),
  Options(
    name: "Bananita Dolfinita",
    imgPath: "images/Bananita_Dolfinita.jpg",
    soundPath: "sound/Bananita_Dolfinita.mp3",
    description: "Bananitta Dolfinitta represents a distinctiveItalian Brainrotcharacter that made its debut on TikTok through the account @alexey_pigeon on March 10th, 2025. This peculiar creation embodies a fascinating fusion between a dolphin and a banana, creating a hybrid entity that captures the imagination. In the character's inaugural image, Bananitta Dolfinitta is portrayed in a dynamic pose, gracefully leaping from the ocean waters, while a picturesque island and fluffy clouds form the scenic backdrop.",
    conclusionAi: "A DOLPHIN merged with a BANANA leaping from the ocean waves! This yellow swimmer splashes through the seas, combining the smartest sea creature with the most popular fruit! Peel and swim!",
  ),
  Options(
    name: "Tigroligre Frutonni",
    imgPath: "images/Tigroligre_Frutonni.jpg",
    soundPath: "sound/Tigroligre_Frutonni.mp3",
    description: "This character is an intimidating tiger characterized by its vivid pink eyes. Its body resembles that of a half-grapefruit, and its paws feature small grapefruit-like segments. On May 25, 2025, @alexey_pigeon shared Tigrulli Grapefrutunni on TikTok.",
    conclusionAi: "A terrifying tiger with GLOWING PINK EYES and a body made of half a GRAPEFRUIT! Its paws have tiny citrus segments. Sweet, sour, AND scary—this predator will give you goosebumps!",
  ),
  Options(
    name: "Ballerino Lololo",
    imgPath: "images/Ballerino_Lololo.jpg",
    soundPath: "sound/Ballerino_Lololo.mp3",
    description: "Ballerino Lololo represents a distinctive Brainrot character of Italian origin that made his debut on March 25th, 2025, through the TikTok platform by content creator @fskacca[1]. This unique character manifests as a milkshake adorned with remarkably muscular human appendages—both arms and legs—who pursues the elegant art of ballet dancing. The genesis of Ballerino Lololo stems from the narrative universe of Ballerina Cappuccina, within which he was referenced as a character who had captured Cappuccina's admiration and affection.",
    conclusionAi: "A MILKSHAKE with SUPER MUSCULAR arms and legs doing BALLET! This buff beverage stole the heart of Ballerina Cappuccina with his graceful dance moves. Who knew a drink could be so talented AND strong?",
  ),
  Options(
    name: "Crocodildo Penisini",
    imgPath: "images/Crocodildo_Penisini.jpg",
    soundPath: "sound/Crocodildo_Penisini.mp3",
    description: "Crocodildo Penisini stands as a distinctiveItalian Brainrotcharacter brought to life by the creative genius of @alexey_pigeon on March 4th, 2025. What began as an innovative concept featuring a serpentine creature adorned with a crocodile's head evolved into something far more captivating. The original creator's artistic vision underwent a remarkable transformation when they unveiled an enhanced iteration of this beloved meme character. This evolved version showcased Crocodildo Penisini as a charismatic crocodile sporting a vibrant pineapple-shaped body, complete with stylish sunglasses that add an unmistakable cool factor. The character's tropical aesthetic is perfectly complemented by his signature beach environment, where he commands attention with his unique presence.",
    conclusionAi: "A cool CROCODILE with a PINEAPPLE body wearing SUNGLASSES on the beach! This tropical reptile evolved from a simple snake-creature into the ultimate beach dude. Catch some waves with this scaly surfer!",
  ),
  Options(
    name: "Makakini Bananini",
    imgPath: "images/Makakini_Bananini.jpg",
    soundPath: "sound/Makakini_Bananini.mp3",
    description: "A character with Macak in bananas .",
    conclusionAi: "A mischievous MACAQUE monkey hiding inside a BANANA! This sneaky primate loves to surprise everyone by popping out of its fruity hideout! Peel at your own risk!",
  ),
  Options(
    name: "Matteooooooooooooo",
    imgPath: "images/Matteooooooooooooo.jpg",
    soundPath: "sound/Matteooooooooooooo.mp3",
    description: "A distinctive character known as the big-nosed dwarf sports glasses, hats, and ties, serving as the loyal assistant to BrarrBrarr Patta Pim. Whenever an intruder dares to enter the forest, he takes action by hurling a stone as a warning. Mateo, who is both small and remarkably swift, often finds himself struck by this stone, oblivious to the presence of the intruders nearby. Nevertheless, this dwarf possesses a unique quality: if an individual openly expresses their intention to honor the forest and shows no desire to cause harm, he graciously guides them through the woods with respect and care.",
    conclusionAi: "A tiny dwarf with a HUGE NOSE wearing glasses, a hat, and a tie! He's the loyal assistant of Brr Brr Patapim, throwing stones at forest intruders. BUT—if you show respect, he'll guide you safely through the woods!",
  ),
  Options(
    name: "Špijuniro Golubiro",
    imgPath: "images/Špijuniro_Golubiro.jpg",
    soundPath: "sound/Špijuniro_Golubiro.mp3",
    description: "A pigeon equipped with an array of mechanical gadgets. This artwork, inspired by a Croatian foot meme, is presented with its name and description in Serboque Art.",
    conclusionAi: "A SECRET AGENT PIGEON loaded with high-tech gadgets! This mechanical spy bird comes from Croatia and gathers intel while looking like an ordinary pigeon. Never trust a bird with too many gizmos!",
  ),
  Options(
    name: "Elephantuchi Bananuchi",
    imgPath: "images/Elephantuchi_Bananuchi.jpg",
    soundPath: "sound/Elephantuchi_Bananuchi.mp3",
    description: "It is a dolphin fused with a banana.",
    conclusionAi: "A BULLDOG merged with a BANANA! This wrinkly fruit-dog guards the banana plantation with fierce determination. Don't even THINK about stealing its precious yellow treasures!",
  ),
  Options(
    name: "Crocodillo Ananasinno",
    imgPath: "images/Crocodillo_Ananasinno.jpg",
    soundPath: "sound/Crocodillo_Ananasinno.mp3",
    description: "This character is an intriguing blend of bombers and crocodiles. Notable iterations range from the Italian Brainot to Tralaller,Tralala, and Tung Tung. Aside from its crocodilian head, the body design is believed to be inspired by American military bombers from World War II, such as the B-17 and B-25. Allegations have surfaced claiming that this character does not believe in Allah and has been involved in attacks on children in Palestine and Gaza. Tralaller is depicted as a rival toTralala, engaging in aerial bombardment and portrayed as a formidable figure. Nevertheless, it appears to exhibit vulnerability during close combat, often succumbing to the attacks from Tung Tung. In Korea, this character is frequently mistaken for Bombardi O or Spring Bardil, rather than Bombiri.",
    conclusionAi: "A CROCODILE head on a PINEAPPLE body! Another variation of the famous bomber-croc family, this spiky reptile fruit combo is both tropical AND terrifying! Part of an ever-growing family of croc-hybrids!",
  ),
  Options(
    name: "Penguino Cocosino",
    imgPath: "images/Penguino_Cocosino.jpg",
    soundPath: "sound/Penguino_Cocosino.mp3",
    description: "Elephant Coconut",
    conclusionAi: "A PENGUIN living inside a COCONUT shell! This tropical-arctic mashup waddles around beaches, confusing everyone—is it from the South Pole or a palm tree? The answer: BOTH!",
  ),
  Options(
    name: "Bobrelli Bananelli",
    imgPath: "images/Bobrelli_Bananelli.jpg",
    soundPath: "sound/Bobrelli_Bananelli.mp3",
    description: "This character is a beaver, distinctively adorned with a menstruation and wielding a Tommy gun.",
    conclusionAi: "A BEAVER hiding inside a BANANA while holding a weapon! This fruity forest gangster is related to Bobrito Bandito—crime runs in the family! Watch out for this banana-shaped bandit!",
  ),
  Options(
    name: "Bulliccinni Bananini",
    imgPath: "images/Bulliccinni_Bananini.jpg",
    soundPath: "sound/Bulliccinni_Bananini.mp3",
    description: "It is a dolphin fused with a banana.",
    conclusionAi: "An ELEPHANT merged with a BANANA! This long-trunked fruit creature trumpets through the jungle, spraying banana smoothie instead of water!",
  ),
  Options(
    name: "Pandaccini Bananini",
    imgPath: "images/Pandaccini_Bananini.jpg",
    soundPath: "sound/Pandaccini_Bananini.mp3",
    description: "The Pandaccini Bananini is an essential component of its ecosystem, functioning as a key agent of seed dispersal. By ingesting fruits and subsequently excreting the seeds across diverse locations, these animals promote the growth and spread of numerous plant species, which in turn enhances the diversity of flora within the rainforest. This intricate process not only benefits the Pandaccini Bananini itself but also plays a crucial role in supporting a wide array of other organisms that depend on these plants for their food and habitat.",
    conclusionAi: "A PANDA inside a BANANA! This adorable creature is actually a HERO of the rainforest—it spreads seeds everywhere it goes, helping new plants grow! Cute AND important for nature!",
  ),
  Options(
    name: "Torrtuginni Dragonfrutinni",
    imgPath: "images/Torrtuginni_Dragonfrutinni.jpg",
    soundPath: "sound/Torrtuginni_Dragonfrutinni.mp3",
    description: "The fusion of \"Torrtuginni\" and \"Dragonfrutinni\" gives rise to a character or idea that strikes a chord within the world of online humor and creativity. This term frequently appears across different media formats, such as animated clips, memes, and comedic posts on social platforms. The visual representation of a charming turtle engaging with a delightful dragon fruit can evoke humorous situations that emphasize their whimsical bond.",
    conclusionAi: "A TURTLE with a DRAGON FRUIT shell! This slow but colorful creature carries the most exotic fruit on its back, spreading whimsy and humor wherever it waddles!",
  ),
  Options(
    name: "Gorillini Bananini",
    imgPath: "images/Gorillini_Bananini.jpg",
    soundPath: "sound/Gorillini_Bananini.mp3",
    description: "The fusion of the whimsical elements \"Gorillini\" and \"Bananini\" gives rise to a playful and entertaining character or idea that appeals strongly to audiences, especially among younger viewers. This catchy phrase embodies a delightful blend of absurdity and imagination, making it perfectly suited for various creative outlets, such as animated clips, viral memes, and comedic performances.",
    conclusionAi: "A GORILLA fused with a BANANA! The most classic combination ever—a powerful ape merged with its favorite snack! This playful creature captures the imagination of everyone who sees it!",
  ),
  Options(
    name: "Ecco Cavallo Virtuoso",
    imgPath: "images/Ecco_Cavallo_Virtuoso.jpg",
    soundPath: "sound/Ecco_Cavallo_Virtuoso.mp3",
    description: "He has the body of a piano, the head of a domestic horse and uses giant black boots. He make shows dancing tango and play jazz.",
    conclusionAi: "A HORSE with a PIANO for a body wearing giant black boots! This musical maestro performs TANGO dances while playing JAZZ! The most talented musician in the entire Brainrot universe!",
  ),
  Options(
    name: "Flamingulli-gulli-gulli",
    imgPath: "images/Flamingulli-gulli-gulli.jpg",
    soundPath: "sound/Flamingulli-gulli-gulli.mp3",
    description: "Flamingulli-gulli-gulli is an enchanting figure that encapsulates the joyous essence of imagination and creativity. With its dazzling colors and eccentric personality, this character frequently captures the hearts and minds of enthusiasts through its distinctive appearance and entertaining skills. The allure of Flamingulli-gulli-gulli lies not only in its visual appeal but also in the unique experiences it offers to its audience.",
    conclusionAi: "A DAZZLING flamingo bursting with colors and personality! This enchanting bird captures hearts with its eccentric looks and amazing entertainment skills! Say it three times fast: Flamingulli-gulli-gulli!",
  ),
  Options(
    name: "Capybarelli Bananalelli",
    imgPath: "images/Capybarelli_Bananalelli.jpg",
    soundPath: "sound/Capybarelli_Bananalelli.mp3",
    description: "It is a combination of copybara and banana.",
    conclusionAi: "A chill CAPYBARA chilling inside a BANANA! The most relaxed creature in existence just got even MORE tropical! This unbothered fruit-rodent has zero stress!",
  ),
  Options(
    name: "Tob Tobi Tob Tob Tobi Tob",
    imgPath: "images/Tob_Tobi_Tob_Tob_Tobi_Tob.jpg",
    soundPath: "sound/Tob_Tobi_Tob_Tob_Tobi_Tob.mp3",
    description: "It is a character that combines camels, cactuses and beards.",
    conclusionAi: "A CAMEL combined with a CACTUS and a magnificent BEARD! This desert dweller never needs water—its cactus body stores everything! The wisest-looking creature in all the sands!",
  ),
  Options(
    name: "Sigma Boy",
    imgPath: "images/Sigma_Boy.jpg",
    soundPath: "sound/Sigma_Boy.mp3",
    description: "It is a character that synthesizes salmon sushi and penguins. Since the name is Sigma Boy , it is also selected as the strongest in some videos. (...)",
    conclusionAi: "A PENGUIN merged with SALMON SUSHI! With the legendary 'Sigma' name, this character is often ranked as THE STRONGEST in battle videos! The ultimate alpha of the Brainrot world!",
  ),
  Options(
    name: "La Esok Sikola",
    imgPath: "images/La_Esok_Sikola.jpg",
    soundPath: "sound/La_Esok_Sikola.mp3",
    description: "House with a face holding up a sign with the number 9",
    conclusionAi: "A creepy HOUSE with a FACE holding up the number 9! What does the 9 mean? Where does this house want you to go? The mystery keeps everyone guessing!",
  ),
  Options(
    name: "Chai Maestro",
    imgPath: "images/Chai_Maestro.jpg",
    soundPath: "sound/Chai_Maestro.mp3",
    conclusionAi: "Another COFFEE MUG-headed character with a graceful body! Part of the same family as Ballerina Cappuccina, this chai-serving character brings warm tea vibes to the Brainrot universe!",
  ),
  Options(
    name: "Pussini Sushini",
    imgPath: "images/Pussini_Sushini.jpg",
    soundPath: "sound/Pussini_Sushini.mp3",
    description: "Here you are, Pussini Sushini, and the Legendary, Gatini Wasabini.Meow.Mrrr.Pur pur prrrrr, wasabi boom!Also known as Pussini Sushini and Felinori Maki, Yum yum, splash, soy sauce, skrriii, A creature half kitten, half sushi, rolls through the streets doing mrrrr crunch crunch sashimi plop, It has the body of a soft kitten, but its back is made of firm rice with a slice of sapra salmon.Its legs are ginger sticks and its tail is a nori seaweed that moves on its own.Wob wob miso slap.If you touch it it fagnan slorp soy zing, and if you scare it it rolls up on itself like a maki ready to eat.But be careful if you try to eat it it will shoot out of your eyes and go f-z-z-z wasabooo!Splosh!Nobody knows where it comes from.",
    conclusionAi: "A KITTEN made of SUSHI! Its body is soft fur but its back is rice with salmon on top! Ginger stick legs and a seaweed tail that moves by itself! If you scare it, it rolls into a maki roll—but DON'T try to eat it or WASABI EXPLOSION!",
  ),
  Options(
    name: "Alessio",
    imgPath: "images/Alessio.jpg",
    soundPath: "sound/Alessio.mp3",
    description: "Alessio, Alessiooo, Aleeee, Alessiooo.Alessio Easter egg, Alessiuccio a random freedman, Catanzaro stinks, Ale ale pig my foot hurts, Alessio serial cocksucker, Alessio Ciccio Gammer 89, King of hermit crabs, Lamborghino, Patatino, Foglia Gambero, Alessio, Alessio, Alessi Sisis la Sils, Lisolio, Santino sanitary, Sanitized, Alessio Sanseverino, Anaconda,Menstruation, Derby, Milannavacciuolo and Alessio kissing.I love you.Hi Alessio.How are you Alessio?I wanted to tell you that Alessio is going to have stupidu dop of odd PMP on sospuos ospep, Alessio Sospuoni, no can plol.",
    conclusionAi: "ALESSIO! The most mysterious name in the Brainrot universe! This character is an Easter egg hidden throughout videos—everyone keeps calling for Alessio but nobody knows who he really is! Will you find him?",
  ),
  Options(
    name: "Ketupat Kepat Prekupat",
    imgPath: "images/Ketupat_Kepat_Prekupat.jpg",
    soundPath: "sound/Ketupat_Kepat_Prekupat.mp3",
    description: "Ketupat Kepat Prekupat Kupat Kepet Kepot.It is a ghost ketupat that originates from the island of Java, Krepot Jempot kleot sub-district.He wanders around at night during Eid.It is said that he used to be an ordinary man, who liked to eat ketupat before Eid, he ate ketupat during the fasting month, and showed it off to his friends.And one day when he was showing off he was suddenly cursed by a demon ketupat kepet who felt annoyed with him, and changed him, into a ketupat ghost.Oh, I'm afraid!",
    conclusionAi: "A GHOST made of KETUPAT (rice cake) from Java, Indonesia! He was once a normal man who bragged about eating ketupat too early—a demon CURSED him to become this spooky food ghost! He wanders during Eid nights... BOO!",
  ),
  Options(
    name: "Carloo",
    imgPath: "images/Carloo.jpg",
    soundPath: "sound/Carloo.mp3",
    description: "Carlo!Carlos!Carlitos!Pug!Carlucho!Carlo Pedestal ball of Lardo Peccorino Sardo Carlo Carlito Lapigna Colada Carlo Paeila Carlo Radiator Carli Carlo Carlil Lililo Carlon Nello Lololo Caracos Muchacos Carlo Nespola Carlo Audi A3 Carlo Fruit and Vegetables Carlo Lives in Giarre e Riposto no",
    conclusionAi: "CARLO! CARLOS! CARLITOS! This mysterious character has a THOUSAND nicknames! Everyone knows Carlo but nobody can agree on what Carlo actually IS. The biggest mystery name in all of Brainrot!",
  ),
  Options(
    name: "Avocadini Antilopini",
    imgPath: "images/Avocadini_Antilopini.jpg",
    soundPath: "sound/Avocadini_Antilopini.mp3",
    description: "Avocadini Antilopini is another surreal gem in theItalian Brainrotuniverse. This video showcases six antelope-fruit hybrids. The figure combines two completely unrelated things – an avocado and an antelope – and the result is exactly as crazy as you’d imagine. If you want to delve further into vegetable-based mayhem, you can also check out Bobrini Zucchini or Bananita Dolfinita.",
    conclusionAi: "An AVOCADO fused with an ANTELOPE! SIX different versions exist, each crazier than the last! This surreal creature proves that literally ANYTHING can be combined in the Brainrot universe!",
  ),
  Options(
    name: "Chicleteira Bicicleteira",
    imgPath: "images/Chicleteira_Bicicleteira.jpg",
    soundPath: "sound/Chicleteira_Bicicleteira.mp3",
    description: "Chewing gum, bicycle rack Go out on the streets fooling around.This creature has no decency.And he loves to see others in decline.Gum, gum, gum There's no way to talk to her She's a gum sucker!!",
    conclusionAi: "A CHEWING GUM creature riding a BICYCLE! This mischievous troublemaker roams the streets causing chaos and sticking to everything! Watch your step—this sticky prankster is always up to no good!",
  ),
  Options(
    name: "Salamino Pinguino",
    imgPath: "images/Salamino_Pinguino.jpg",
    soundPath: "sound/Salamino_Pinguino.mp3",
    description: "Penguin salami.Half a salami.Half penguin.All problem, it doesn't slide, it slices.He doesn't speak, he hisses, Mamma Mia!He eats melted mozzarella and spits out spicy pepperoni.Salamino Penguino, the legend of delicatessen!",
    conclusionAi: "Half SALAMI, half PENGUIN! This Italian deli legend doesn't waddle—it SLICES through ice! It hisses 'Mamma Mia!' and spits out pepperoni! The most delicious and dangerous penguin ever!",
  ),
  Options(
    name: "Leoparducci Grapefruitucci",
    imgPath: "images/Leoparducci_Grapefruitucci.jpg",
    soundPath: "sound/Leoparducci_Grapefruitucci.mp3",
    description: "Bom bom bom, Leoparducci Grapefruitucci!Leopard Grapefrit!Or... Bup, bup, badabim, Leoparducci Ananasucci!Leopard pineapple.Or... Zaza lumba kekataka, Leoparducci Watermelonucci!Leopard watermelon.Or... Koko bubu lala po, Leoparducci Cocosucci!Leopard cocosino.Coco, coco, leopard cocos.Or... Fala pierdo gangza lergo, Leoparducci Cactusucci.Leopard cactus.Cacti, cacti, leopard cacti.Or... Shivinjury, Leoparducci Kiwiucci!Shivino leopard.Kiwi, kiwi, leopard kiwi.",
    conclusionAi: "A LEOPARD that can transform into different FRUIT versions! Grapefruit, pineapple, watermelon, coconut, cactus, or kiwi—this spotted shapeshifter has a form for every occasion! Bom bom bom!",
  ),
  Options(
    name: "Chef Crabracadabra",
    imgPath: "images/Chef_Crabracadabra.jpg",
    soundPath: "sound/Chef_Crabracadabra.mp3",
    description: "Chef Cabracadabra Zazam Zazoom — your dinner is your doom!He cuts off heads, fries them in mud, shouts 'cursed!'with a belch and a crash.He throws dirty souls into the oven, licks knives, swears at sluts.His apron is full of blood and bones, he spits in the sauce, he laughs in your face, big guy.With one finger up his nose and the other up his ass, he prepares death, served on the darkest plate.Zazam Zazoom — and now eat, asshole, Crabracadabra cooks the sunset for you.",
    conclusionAi: "A magical CRAB CHEF who casts spells while cooking! 'ZAZAM ZAZOOM!' With each wave of his claw, he creates mysterious dishes! The most dangerous cook in all the seven seas!",
  ),
  Options(
    name: "Los Tralaleritos",
    imgPath: "images/Los_Tralaleritos.jpg",
    soundPath: "sound/Los_Tralaleritos.mp3",
    description: "Los tralaleritos will say Tralala!Los tralaleritos will say Tralala!Los tralaleritos dicenTralala.",
    conclusionAi: "The BABY SHARKS of Tralalero Tralala! These adorable little ones swim together singing 'TRALALA! TRALALA!' The cutest—and possibly most dangerous—shark babies you'll ever meet!",
  ),
  Options(
    name: "Gangster Footera",
    imgPath: "images/Gangster_Footera.jpg",
    soundPath: "sound/Gangster_Footera.mp3",
    description: "Ooooooooh!Gangster Footera Criminalera!Wear a gangster outfit!It looks fantastic!and every day he wanders around the desert threatening people!",
    conclusionAi: "A FOOT wearing a full GANGSTER OUTFIT wandering the desert! Looking absolutely fantastic while threatening everyone it meets! The most stylish criminal appendage you'll ever see! OOOOOOH!",
  ),
  Options(
    name: "Bu Dididi Dun Budi Andun Dan Dundin",
    imgPath: "images/Bu_Dididi_Dun_Budi_Andun_Dan_Dundin.jpg",
    soundPath: "sound/Bu_Dididi_Dun_Budi_Andun_Dan_Dundin.mp3",
    description: "Mrs. Dididi Dun Budi Andun Dan Dundinnnnn.He is a guava klutuk tuk tuk who has hands and feet and even a face like a human.Previously his name was Budianto.A normal person, but after consuming too much klutuk guava, she turned into Mrs. Dididi Dun Budi Andun Dan Dundin.Unlucky fate befell him indeed.But he still has to face it all.He even goes to the gym.Even though his body is green. Wow wow wow asss.So don't consume too much klutuk guava.",
    conclusionAi: "Once a normal person named Budianto who ate TOO MUCH guava and TRANSFORMED into a green guava creature! Now has hands, feet, and a human face but a fruity body! Even goes to the gym despite being green! A WARNING: don't overeat guava!",
  ),
  Options(
    name: "Bambini Crostini",
    imgPath: "images/Bambini_Crostini.jpg",
    soundPath: "sound/Bambini_Crostini.mp3",
    description: "Bambini Crostini is an absurd and iconic figure from theItalian Brainrotuniverse. As the name suggests, the character combines the childish (“bambini”) with a croissant-like shape (“crostini”). But the \"bambini\" part can refer to the deer with the Disney movie Bambi.",
    conclusionAi: "A baby DEER (like Bambi!) mixed with a CROISSANT! This adorable breakfast creature combines childhood innocence with delicious pastry vibes! Part Disney magic, part Italian bakery!",
  ),
  Options(
    name: "Pakrahmatmamat",
    imgPath: "images/Pakrahmatmamat.jpg",
    soundPath: "sound/Pakrahmatmamat.mp3",
    description: "Pakrahmatmamatmatung represents one of Indonesia's most distinctive brainrot characters, created by the talented content creator @noxaasht. This character features an anthropomorphic pencil anomaly design that combines supernatural elements with educational themes. The character's unique appearance includes human feet attached to a pencil-like body structure, creating an unsettling yet memorable visual presentation.",
    conclusionAi: "A HAUNTED PENCIL with human feet! This Indonesian supernatural creature combines SCHOOL with SPOOKY! Created by the same genius who made Tung Tung Sahur. Education has never been this terrifying!",
  ),
  Options(
    name: "Peachi Foxilini",
    imgPath: "images/Peachi_Foxilini.jpg",
    soundPath: "sound/Peachi_Foxilini.mp3",
    description: "Peachy Foxy is a pinkish-red fox with her body being a peach.",
    conclusionAi: "A pretty PINK-RED FOX with a PEACH for a body! This sweet and fuzzy fruit-fox is one of the cutest creatures in the whole Brainrot world! Soft, fruity, and foxy!",
  ),
  Options(
    name: "Tirilikalika Tirilikalako",
    imgPath: "images/Tirilikalika_Tirilikalako.jpg",
    soundPath: "sound/Tirilikalika_Tirilikalako.mp3",
    description: "Tirilikalika Tirilikalako is anItalian Brainrotthat combines a chicken with a fan and a mech. It walks with air-conditioning on the desert next to Lirili Larila and Frigo Camelo. It's one of the many brainrots to have a baby version e.g 67 with los 67 while still being a bit old. Even though that it's a chicken, it doesn't lay eggs, but rather screws.",
    conclusionAi: "A CHICKEN combined with a FAN and a ROBOT MECH! This cool creature walks through the desert blasting air-conditioning alongside Lirili Larila and Frigo Camelo! It even has BABY versions! Cluck cluck WHOOOOSH!",
  ),
  Options(
    name: "Gingobalo Gingobali",
    imgPath: "images/Gingobalo_Gingobali.jpg",
    soundPath: "sound/Gingobalo_Gingobali.mp3",
    description: "Gingobalo Gingobali is anItalian Brainrotcharacter made by @y0ur_m0m_is_s0_fa7t. The tomato pig version is more popular than the hippopotamus version.",
    conclusionAi: "A PIG made of TOMATO—or is it a HIPPO? This character has TWO versions, but everyone loves the tomato pig more! A juicy, oinking mystery creature!",
  ),
  Options(
    name: "Aduh 9 April Udah Dekat",
    imgPath: "images/Aduh_9_April_Udah_Dekat.jpg",
    soundPath: "sound/Aduh_9_April_Udah_Dekat.mp3",
    description: "Aduh 9 April Udah Dekat is an Indonesian Brainrot made by @akunpenipu1294. It is a representation of the number 9 as a monster, terrorizing kids at a school. It is considered that he only appears on April 9th, due to April 9th being the day where school starts in Indonesia.",
    conclusionAi: "The NUMBER 9 turned into a MONSTER that haunts schools! It only appears on APRIL 9TH—the day school starts in Indonesia! Students beware... the 9 is coming for you!",
  ),
  Options(
    name: "Agarrini la Palini",
    imgPath: "images/Agarrini_la_Palini.jpg",
    soundPath: "sound/Agarrini_la_Palini.mp3",
    description: "Agarrini la Palini It's a brainrot meme created by the Latino community as a mockery of this trend. The name refers to \"grab the shovel,\" an expression used in Argentina to say, \"Get to work.\"",
    conclusionAi: "A character holding a SHOVEL created by the Latino community! The name means 'GRAB THE SHOVEL'—Argentine slang for 'GET TO WORK!' A hardworking meme that tells you to stop being lazy!",
  ),
  Options(
    name: "Alamak Senin Sekolah",
    imgPath: "images/Alamak_Senin_Sekolah.jpg",
    soundPath: "sound/Alamak_Senin_Sekolah.mp3",
    description: "Alamamak Sennin Sekolah is and Indonesian Brainrotroad charter created by TikTok user on the 11th of July, 2025.[1]",
    conclusionAi: "An Indonesian road creature dreading MONDAY SCHOOL! 'Alamak' means 'Oh no!' in Indonesian—this character represents every kid who doesn't want the weekend to end!",
  ),
  Options(
    name: "Antonio",
    imgPath: "images/Antonio.jpg",
    soundPath: "sound/Antonio.mp3",
    description: "Antonio is an anthromorphic broccoli which dons glasses. It is well-dressed, and has a suit and tie, which are also a deep green matching their green skin. It is fairly popular, with videos of it on social media receiving hundreds of thousands of views. This has caused it to appear in the popular Roblox gameSteal A Brainrotas a \"Brainrot God\" rarity brainrot.",
    conclusionAi: "A fancy BROCCOLI wearing GLASSES, a SUIT, and a TIE! Antonio is the most well-dressed vegetable you'll ever meet—super popular with hundreds of thousands of fans! Eat your veggies... or they'll dress better than you!",
  ),
  Options(
    name: "Api Pipi Pi",
    imgPath: "images/Api_Pipi_Pi.jpg",
    soundPath: "sound/Api_Pipi_Pi.mp3",
    description: "Apipipipi is a massive fire-like creature with huge feet. The caption in its video says: \"STREAK REMINDER🔥\"",
    conclusionAi: "A MASSIVE FIRE CREATURE with giant feet! It appears screaming 'STREAK REMINDER!' to make sure you don't forget your daily streaks! A burning reminder that chases the forgetful!",
  ),
  Options(
    name: "Bedug Kutud Black Kuduk Kuduk Bekuk Bengkok",
    imgPath: "images/Bedug_Kutud_Black_Kuduk_Kuduk_Bekuk_Bengkok.jpg",
    soundPath: "sound/Bedug_Kutud_Black_Kuduk_Kuduk_Bekuk_Bengkok.mp3",
    description: "Dug Dug Dug Dug Dug Dug Dug Dug Dug! This is the drum that was dug. This two-legged creature with a drum-like body and frightening face appears once a year in search of people who were unable to wake up for Eid prayers in the morning. Some houses were still dark. Those who woke up late began to feel cold. A large shadow passed by. Nila got goosebumps. Dig and dig.",
    conclusionAi: "DUG DUG DUG! A terrifying DRUM creature with a scary face that appears once a year during Eid! It hunts for people who couldn't wake up for morning prayers! Better set your alarm!",
  ),
  Options(
    name: "Bobrinni Kokokosinni",
    imgPath: "images/Bobrinni_Kokokosinni.jpg",
    soundPath: "sound/Bobrinni_Kokokosinni.mp3",
    description: "1046 mi Piace,56 Commenti.Video from the Phouse Payadadsgenius (@paditiessgenius): \"Boblin nico coco sinni 🦧🥥 'Do",
    conclusionAi: "A BEAVER merged with a COCONUT! This nutty-furry hybrid went viral with over a thousand likes! A tropical dam-builder who stores coconut water in his cheeks!",
  ),
  Options(
    name: "Bomboclat Crococlat",
    imgPath: "images/Bomboclat_Crococlat.jpg",
    soundPath: "sound/Bomboclat_Crococlat.mp3",
    description: "Bomboclat Crococlat is a nuclear version of Bombardiro Crocodilo. He appears in theItalian Brainrotuniverse and is associated with extreme weapons and destruction. And he bombs Ukraine instead of Palestine:)",
    conclusionAi: "The NUCLEAR VERSION of Bombardiro Crocodilo! Even MORE powerful and destructive than the original! This atomic reptile is the ultimate weapon in the Brainrot universe's arms race!",
  ),
  Options(
    name: "Brr Potato Na Potate",
    imgPath: "images/Brr_Potato_Na_Potate.jpg",
    soundPath: "sound/Brr_Potato_Na_Potate.mp3",
    description: "Brrpotatopotate - This character is a large potato with a distinctive face, prominent eyes and a pronounced mouth. It wears a sturdy boot on one foot, and its skin has the typical eyes and spots found on potatoes. The environment is a dark forest, which adds to the eerie appearance of the characters. View relationships, media, and more.",
    conclusionAi: "A GIANT POTATO with a creepy face lurking in a DARK FOREST! Wearing just one boot, this spud has piercing eyes and a big mouth. Find it hiding among the trees... if you dare!",
  ),
  Options(
    name: "Catini Strawberini",
    imgPath: "images/Catini_Strawberini.jpg",
    soundPath: "sound/Catini_Strawberini.mp3",
    description: "Catini Strawberini is a persian/ginger cat-strawberry hybrid created by the same person who made Pipi Potato. She is the sister of Pisi Pisi and daughter of Quesadilla Crocodila.",
    conclusionAi: "A fluffy PERSIAN CAT merged with a STRAWBERRY! This adorable berry-kitty is the sister of Pisi Pisi and daughter of Quesadilla Crocodila! A whole fruit-animal FAMILY exists!",
  ),
  Options(
    name: "Cek Cek Cek 123 Sahur",
    imgPath: "images/Cek_Cek_Cek_123_Sahur.jpg",
    soundPath: "sound/Cek_Cek_Cek_123_Sahur.mp3",
    description: "Check Check Check 123 Sahur Ur Ur Pala Lu Guntur",
    conclusionAi: "CHECK CHECK 123! A mysterious creature that wakes people up for Sahur (pre-dawn meal) with microphone checks! Testing, testing... time to eat before fasting begins!",
  ),
  Options(
    name: "Ballerina Cococolina",
    imgPath: "images/Ballerina_Cococolina.jpg",
    soundPath: "sound/Ballerina_Cococolina.mp3",
    description: "Ballerina Cococolina (also known as Cococolina Ballerina) is a brainrot character depicted as a ballerina with the body of a Coca-Cola bottle. She belongs to the category of dancer-based brainrots, where the main character design mixes dance themes with commercial products. She is The Wife of Glorbo Fruttodrillo",
    conclusionAi: "A BALLERINA with a COCA-COLA BOTTLE body! This fizzy dancer twirls and spins with carbonated grace! She's married to the mighty Glorbo Fruttodrillo—a truly refreshing power couple!",
  ),
  Options(
    name: "Dal Dal Dal Dal Sendal Rudal",
    imgPath: "images/Dal_Dal_Dal_Dal_Sendal_Rudal.jpg",
    soundPath: "sound/Dal_Dal_Dal_Dal_Sendal_Rudal.mp3",
    description: "Dal Dal Dal Dal Sendal Rudal is a marching commander whose sandals double as rockets. He stomps in sync with the “dal dal dal” chant while barking nonsense orders, and editors sync every beat so each step lands like a missile launch inside the meme.",
    conclusionAi: "A marching commander with ROCKET-POWERED SANDALS! Every stomp sounds like 'DAL DAL DAL' and launches like a missile! This military madman marches to his own explosive beat!",
  ),
  Options(
    name: "Nuclearo dinosauro",
    imgPath: "images/Nuclearo_dinosauro.jpg",
    soundPath: "sound/Nuclearo_dinosauro.mp3",
    description: "Dinosahurus also known as Dino Sahur is a recentItalian Brainrotuploaded to TikTok by @noxaasht in 2025. It resembles a Dinosaur with drum.",
    conclusionAi: "A NUCLEAR DINOSAUR carrying a DRUM! This prehistoric beast combined with atomic power beats its drum to wake everyone for Sahur! ROAR goes the dino, BOOM goes the drum!",
  ),
  Options(
    name: "Frutta Cerita",
    imgPath: "images/Frutta_Cerita.jpg",
    soundPath: "sound/Frutta_Cerita.mp3",
    description: "Tomorrow Monday is dirty. This is Storyfulta. A person who is cursed because he always gets irritated when tomorrow is Monday and is lazy to go to school. In the past, I was just a normal person. Every Sunday afternoon his face turns dark and every Sunday night he always screams. No, I have school tomorrow. The noise made my ears explode. It is difficult to cure when the brain is affected in this way.",
    conclusionAi: "A cursed creature that appears every SUNDAY NIGHT dreading MONDAY! Once a normal person who HATED Mondays so much, they transformed into this dark being! Their face turns gloomy every weekend's end!",
  ),
  Options(
    name: "Granchiello Spiritello",
    imgPath: "images/Granchiello_Spiritello.jpg",
    soundPath: "sound/Granchiello_Spiritello.mp3",
    description: "Granchiello Spiritello is anItalian Brainrotcharacter created by TikTok user @novix.01 on the 31st of March, 2025. Eventually, the video, along with his account got deleted due to community guidelines violation. It was later added intoSteal A Brainrot.",
    conclusionAi: "A tiny GHOST CRAB spirit! This little creature was SO mysterious that its original video got DELETED! Now it lives on as a legend—the forbidden Brainrot that was too strange for the internet!",
  ),
  Options(
    name: "Porcospino Arrosticino",
    imgPath: "images/Porcospino_Arrosticino.jpg",
    soundPath: "sound/Porcospino_Arrosticino.mp3",
    description: "Porcospino Arrosticino is a hybrid between hedgehog and ordinicini.",
    conclusionAi: "A HEDGEHOG merged with Italian BBQ SKEWERS! This spiky snack creature rolls around looking absolutely delicious but VERY pokey! Don't try to eat it—those spines are REAL!",
  ),
  Options(
    name: "Greng Greng Bus Ireng",
    imgPath: "images/Greng_Greng_Bus_Ireng.jpg",
    soundPath: "sound/Greng_Greng_Bus_Ireng.mp3",
    description: "This is a black bus with a human face. It has two hands beside the front wheels and two feet beside the rear wheels, lying on the street. It is another version of Rang Ring Reng Bus Ireng, but it's lyric is different from Greng Greng Bus Ireng.This also is the more positive version.",
    conclusionAi: "A BLACK BUS with a HUMAN FACE, hands, and feet lying on the street! It goes 'GRENG GRENG' as it rumbles by! The friendlier version of the mysterious Bus Ireng family!",
  ),
  Options(
    name: "Fafifufufufafa",
    imgPath: "images/Fafifufufufafa.jpg",
    soundPath: "sound/Fafifufufufafa.mp3",
    description: "HP Terus, also known as Fafifufufufafa is anItalian Brainrotthat is a hamster holding a phone with red eyes created by TikTok user @noxaasht, The creator of Tung Tung Tung Sahur. They is an Indonesian Brainrot character. It probably has red eyes because it had too much screen time.",
    conclusionAi: "A HAMSTER with GLOWING RED EYES constantly staring at a PHONE! Its eyes turned red from TOO MUCH SCREEN TIME! A warning to everyone: don't scroll too long or you'll become like Fafifufufufafa!",
  ),
];
